import { useState, useEffect, useCallback } from 'react';
import {
  Gift, Copy, Check, Share2, Users, Trophy, Loader2, Send,
  Clock, CheckCircle2, XCircle, Mail, X, TrendingUp, Sparkles,
} from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';

interface ReferralRow {
  id: string;
  referral_code: string;
  referred_email: string | null;
  referred_id: string | null;
  status: 'pending' | 'completed' | 'cancelled';
  reward_amount: number;
  completed_at: string | null;
  created_at: string;
}

const REWARD_AMOUNT = 50;

const statusMeta: Record<string, { label: string; icon: typeof Clock; color: string; bg: string; dot: string }> = {
  pending:   { label: 'Pending',   icon: Clock,         color: 'text-amber-700',  bg: 'bg-amber-50',   dot: 'bg-amber-500' },
  completed: { label: 'Completed', icon: CheckCircle2,  color: 'text-emerald-700',bg: 'bg-emerald-50', dot: 'bg-emerald-500' },
  cancelled: { label: 'Cancelled', icon: XCircle,       color: 'text-red-600',   bg: 'bg-red-50',     dot: 'bg-red-500' },
};

const HOW_IT_WORKS = [
  { step: 1, title: 'Share Your Code', desc: 'Send your unique referral code to friends & colleagues', icon: Share2 },
  { step: 2, title: 'They Sign Up',    desc: 'Your referral creates an account using your code',       icon: Users },
  { step: 3, title: 'You Both Earn',    desc: 'Get SLE 50 wallet credit when they complete first booking', icon: Gift },
];

export function ReferralPanel() {
  const { user, profile } = useAuth();
  const [referrals, setReferrals] = useState<ReferralRow[]>([]);
  const [referralCode, setReferralCode] = useState('');
  const [loading, setLoading] = useState(true);
  const [inviteEmail, setInviteEmail] = useState('');
  const [sending, setSending] = useState(false);
  const [sendMsg, setSendMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [copied, setCopied] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);

  const loadReferralCode = useCallback(async () => {
    if (!user) return;
    // The referral code lives on the profiles table (auto-generated by trigger)
    const { data: prof } = await supabase
      .from('profiles')
      .select('referral_code')
      .eq('id', user.id)
      .maybeSingle();
    if (prof?.referral_code) setReferralCode(prof.referral_code);
  }, [user]);

  const loadReferrals = useCallback(async () => {
    if (!user) return;
    setLoading(true);
    const { data } = await supabase
      .from('referrals')
      .select('*')
      .eq('referrer_id', user.id)
      .order('created_at', { ascending: false });
    setReferrals((data as ReferralRow[]) || []);
    setLoading(false);
  }, [user]);

  useEffect(() => { loadReferralCode(); loadReferrals(); }, [loadReferralCode, loadReferrals]);

  const handleCopyCode = async () => {
    if (!referralCode) return;
    await navigator.clipboard.writeText(referralCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyLink = async () => {
    if (!referralCode) return;
    const link = `${window.location.origin}/?ref=${referralCode}`;
    await navigator.clipboard.writeText(link);
    setLinkCopied(true);
    setTimeout(() => setLinkCopied(false), 2000);
  };

  const handleShare = async () => {
    if (!referralCode || !profile) return;
    const shareUrl = `${window.location.origin}/?ref=${referralCode}`;
    const shareText = `Join me on AlphaTek Nexus! Use my referral code ${referralCode}.`;
    if (navigator.share) {
      try { await navigator.share({ title: 'AlphaTek Nexus', text: shareText, url: shareUrl }); } catch { /* cancelled */ }
    } else {
      await navigator.clipboard.writeText(`${shareText}\n${shareUrl}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleInvite = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user || !referralCode) return;
    setSendMsg(null);
    const email = inviteEmail.trim().toLowerCase();
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      setSendMsg({ type: 'error', text: 'Enter a valid email address' });
      return;
    }
    if (email === profile?.email?.toLowerCase()) {
      setSendMsg({ type: 'error', text: "You can't refer yourself" });
      return;
    }
    setSending(true);
    const { data, error } = await supabase.functions.invoke('send-referral-invite', {
      body: { recipientEmail: email, referralCode, referrerId: user.id },
    });
    if (error || (data && !data.success)) {
      const msg = data?.error || error?.message || 'Failed to send invitation';
      setSendMsg({ type: 'error', text: msg });
      if (data?.referralCreated) loadReferrals();
    } else {
      setSendMsg({ type: 'success', text: `Invitation sent to ${email}` });
      setInviteEmail('');
      loadReferrals();
    }
    setSending(false);
  };

  const completed = referrals.filter((r) => r.status === 'completed');
  const totalEarned = completed.reduce((sum, r) => sum + Number(r.reward_amount), 0);
  const pendingCount = referrals.filter((r) => r.status === 'pending').length;
  const invitedCount = referrals.length;

  return (
    <div className="space-y-5">
      {/* ── Hero: Referral Code Card ── */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-rose-500 via-rose-600 to-pink-600 p-6">
        {/* Decorative circles */}
        <div className="absolute -top-8 -right-8 w-32 h-32 bg-white/10 rounded-full" />
        <div className="absolute -bottom-12 -left-12 w-40 h-40 bg-white/5 rounded-full" />

        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-1">
            <Gift className="w-5 h-5 text-white" />
            <h3 className="text-white font-bold text-lg">Refer & Earn</h3>
          </div>
          <p className="text-rose-100 text-sm mb-5">Share your code and earn SLE {REWARD_AMOUNT} for every referral</p>

          {/* Code box */}
          <div className="flex items-center gap-2 mb-3">
            <div className="flex-1 px-4 py-3.5 bg-white/15 backdrop-blur-sm rounded-xl border border-white/20">
              <p className="text-[10px] uppercase tracking-wider text-rose-100 font-medium mb-0.5">Your Referral Code</p>
              <p className="font-mono text-lg sm:text-xl font-bold tracking-wider text-white select-all">
                {referralCode || 'Loading…'}
              </p>
            </div>
            <button
              onClick={handleCopyCode}
              className="flex-shrink-0 w-12 h-[60px] rounded-xl bg-white flex items-center justify-center hover:bg-rose-50 transition-colors group"
              title="Copy code"
            >
              {copied
                ? <Check className="w-5 h-5 text-emerald-600" />
                : <Copy className="w-5 h-5 text-rose-600 group-hover:scale-110 transition-transform" />}
            </button>
          </div>

          {/* Action buttons */}
          <div className="flex gap-2">
            <button
              onClick={handleShare}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-white text-rose-600 text-sm font-semibold rounded-xl hover:bg-rose-50 transition-colors"
            >
              <Share2 className="w-4 h-4" />
              Share
            </button>
            <button
              onClick={handleCopyLink}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-white/15 backdrop-blur-sm text-white text-sm font-semibold rounded-xl border border-white/20 hover:bg-white/25 transition-colors"
            >
              {linkCopied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {linkCopied ? 'Copied!' : 'Copy Link'}
            </button>
          </div>
        </div>
      </div>

      {/* ── Stats Row ── */}
      <div className="grid grid-cols-3 gap-2 sm:gap-3">
        <StatCard icon={Trophy}     value={`SLE ${totalEarned}`} label="Total Earned" color="text-emerald-600" bg="bg-emerald-50" />
        <StatCard icon={Users}      value={invitedCount}         label="Invited"       color="text-blue-600"    bg="bg-blue-50" />
        <StatCard icon={TrendingUp} value={pendingCount}         label="Pending"       color="text-amber-600"   bg="bg-amber-50" />
      </div>

      {/* ── Invite by Email ── */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <Mail className="w-4 h-4 text-slate-500" />
          <h4 className="text-sm font-semibold text-slate-800">Invite by Email</h4>
        </div>
        <form onSubmit={handleInvite} className="flex flex-col sm:flex-row gap-2">
          <input
            type="email"
            value={inviteEmail}
            onChange={(e) => setInviteEmail(e.target.value)}
            placeholder="friend@example.com"
            className="flex-1 px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-rose-500 focus:border-rose-500 focus:bg-white outline-none transition-all"
          />
          <button
            type="submit"
            disabled={sending}
            className="flex items-center justify-center gap-2 px-5 py-2.5 bg-slate-900 text-white text-sm font-medium rounded-xl hover:bg-slate-800 transition-colors disabled:opacity-50 w-full sm:w-auto"
          >
            <Send className="w-4 h-4" />
            {sending ? 'Sending…' : 'Send Invite'}
          </button>
        </form>
        {sendMsg && (
          <p className={`text-xs mt-2 flex items-center gap-1.5 ${sendMsg.type === 'success' ? 'text-emerald-600' : 'text-red-600'}`}>
            {sendMsg.type === 'success' ? <CheckCircle2 className="w-3.5 h-3.5" /> : <XCircle className="w-3.5 h-3.5" />}
            {sendMsg.text}
          </p>
        )}
      </div>

      {/* ── How It Works ── */}
      <div className="p-5 bg-gradient-to-br from-slate-50 to-slate-100 rounded-2xl border border-slate-100">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-4 h-4 text-slate-500" />
          <h4 className="text-sm font-semibold text-slate-800">How It Works</h4>
        </div>
        <div className="space-y-4">
          {HOW_IT_WORKS.map(({ step, title, desc, icon: Icon }) => (
            <div key={step} className="flex items-start gap-3">
              <div className="flex-shrink-0 w-9 h-9 bg-white rounded-xl border border-slate-200 flex items-center justify-center shadow-sm">
                <Icon className="w-4 h-4 text-rose-500" />
              </div>
              <div className="flex-1 pt-0.5">
                <div className="flex items-center gap-2">
                  <span className="w-5 h-5 bg-rose-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center">{step}</span>
                  <p className="text-sm font-semibold text-slate-800">{title}</p>
                </div>
                <p className="text-xs text-slate-500 mt-0.5 ml-7">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── Referral History ── */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Users className="w-4 h-4 text-slate-500" />
            <h4 className="text-sm font-semibold text-slate-800">Referral History</h4>
          </div>
          {referrals.length > 0 && (
            <span className="text-xs text-slate-400">{referrals.length} total</span>
          )}
        </div>
        {loading ? (
          <div className="flex items-center justify-center py-8"><Loader2 className="w-5 h-5 text-rose-500 animate-spin" /></div>
        ) : referrals.filter((r) => r.referred_email).length === 0 ? (
          <div className="text-center py-8 bg-slate-50 rounded-xl border border-slate-100">
            <Users className="w-10 h-10 text-slate-200 mx-auto mb-2" />
            <p className="text-sm text-slate-400">No referrals yet</p>
            <p className="text-xs text-slate-400 mt-0.5">Share your code to start earning</p>
          </div>
        ) : (
          <div className="space-y-2">
            {referrals.filter((r) => r.referred_email).map((r) => {
              const meta = statusMeta[r.status];
              const Icon = meta.icon;
              return (
                <div key={r.id} className="flex items-center gap-3 p-3.5 bg-white rounded-xl border border-slate-100">
                  <div className={`w-10 h-10 ${meta.bg} rounded-full flex items-center justify-center flex-shrink-0`}>
                    <Icon className={`w-4 h-4 ${meta.color}`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-slate-700 truncate">{r.referred_email}</p>
                    <p className="text-xs text-slate-400 mt-0.5">
                      {new Date(r.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </p>
                  </div>
                  <div className="text-right flex-shrink-0">
                    <span className={`inline-flex items-center gap-1 text-xs font-medium px-2.5 py-1 rounded-full ${meta.bg} ${meta.color}`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${meta.dot}`} />
                      {meta.label}
                    </span>
                    {r.status === 'completed' && (
                      <p className="text-xs text-emerald-600 font-semibold mt-1">+SLE {r.reward_amount}</p>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

function StatCard({ icon: Icon, value, label, color, bg }: { icon: typeof Trophy; value: string | number; label: string; color: string; bg: string }) {
  return (
    <div className="p-3 sm:p-4 bg-white rounded-xl border border-slate-100 text-center">
      <div className={`w-8 h-8 ${bg} rounded-lg flex items-center justify-center mb-2 mx-auto`}>
        <Icon className={`w-4 h-4 ${color}`} />
      </div>
      <p className="text-base sm:text-lg font-bold text-slate-800">{value}</p>
      <p className="text-[10px] sm:text-xs text-slate-400">{label}</p>
    </div>
  );
}

/** Modal wrapper — renders ReferralPanel inside a centered popup dialog */
export function ReferralModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', handler);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', handler);
      document.body.style.overflow = '';
    };
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm animate-[fadeInUp_0.2s_ease-out]"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative w-full max-w-lg max-h-[90vh] overflow-y-auto bg-white rounded-2xl shadow-2xl animate-[fadeInUp_0.25s_ease-out]">
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between px-5 py-4 bg-white/95 backdrop-blur-md border-b border-slate-100">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-rose-50 rounded-lg flex items-center justify-center">
              <Gift className="w-4 h-4 text-rose-600" />
            </div>
            <h2 className="font-bold text-slate-900">Referral Credits</h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="p-5">
          <ReferralPanel />
        </div>
      </div>
    </div>
  );
}
