/*
# Smart Sort pickups, invoices, and payments

1. Purpose
  Add operational and billing support to the Smart Sort (waste management)
  module. Pickups turn subscriptions into a schedulable, trackable workflow.
  Invoices + payments close the loop from subscription to revenue.

2. New Tables

  `smart_sort_pickups`
    - id (uuid PK)
    - subscription_id (uuid FK -> smart_sort_subscriptions ON DELETE CASCADE)
    - user_id (uuid FK -> auth.users ON DELETE CASCADE) — denormalized for
      fast owner-scoped queries and RLS ownership checks
    - scheduled_date (date, not null) — the planned collection day
    - time_slot (text, not null) — morning / afternoon / evening
    - driver_name (text) — assigned collector (nullable until assigned)
    - route_order (integer) — ordering within a driver's day for route optimization
    - status (text, not null default 'scheduled')
        CHECK IN (scheduled, assigned, in_progress, completed, missed, cancelled)
    - completed_at (timestamptz) — when the pickup was finished
    - notes (text) — driver / admin notes
    - photo_url (text) — proof-of-collection photo (storage URL)
    - created_at, updated_at (timestamptz)

  `smart_sort_invoices`
    - id (uuid PK)
    - subscription_id (uuid FK -> smart_sort_subscriptions ON DELETE CASCADE)
    - user_id (uuid FK -> auth.users ON DELETE CASCADE)
    - invoice_number (text, unique not null) — human-readable e.g. SS-2026-0001
    - period_start (date, not null) — billing period covered
    - period_end (date, not null)
    - amount_sle (integer, not null) — amount due in SLE
    - amount_paid_sle (integer, not null default 0) — running total of payments
    - status (text, not null default 'pending')
        CHECK IN (pending, paid, partial, overdue, void)
    - due_date (date, not null)
    - sent_at (timestamptz) — when the invoice was issued/sent
    - paid_at (timestamptz) — when fully paid
    - created_at, updated_at (timestamptz)

  `smart_sort_payments`
    - id (uuid PK)
    - invoice_id (uuid FK -> smart_sort_invoices ON DELETE CASCADE)
    - user_id (uuid FK -> auth.users ON DELETE CASCADE)
    - amount_sle (integer, not null)
    - method (text, not null)
        CHECK IN (cash, bank_transfer, africell_money, orange_money, qmoney, other)
    - reference (text) — transaction / receipt reference
    - status (text, not null default 'confirmed')
        CHECK IN (pending, confirmed, failed)
    - recorded_by (uuid FK -> auth.users) — admin who recorded it (nullable)
    - created_at (timestamptz)

3. Indexes
  - pickups by scheduled_date (admin daily board)
  - pickups by subscription_id (client history)
  - invoices by status + due_date (overdue detection)
  - invoices by subscription_id
  - payments by invoice_id

4. Security (RLS)
  All tables enabled for RLS.

  smart_sort_pickups:
    - Owner: SELECT/INSERT/UPDATE/DELETE on own pickups (auth.uid() = user_id).
    - Admin: SELECT + UPDATE on all pickups (role = 'admin'). No admin INSERT/
      DELETE to keep ownership of schedule creation with the client/trigger.

  smart_sort_invoices:
    - Owner: SELECT on own invoices. No owner INSERT/UPDATE/DELETE — invoices are
      system/admin-generated to keep numbering and amounts authoritative.
    - Admin: SELECT/INSERT/UPDATE on all invoices.

  smart_sort_payments:
    - Owner: SELECT on own payments.
    - Admin: SELECT/INSERT/UPDATE on all payments (record / confirm payments).

5. Notes
  - `user_id` is denormalized onto pickups, invoices, and payments so RLS
    ownership checks are a single-column compare (auth.uid() = user_id) without a
    join back to subscriptions. This is consistent with the bookings pattern.
  - Invoice numbering is generated by the app/admin at insert time using a
    YYYY-NNNN pattern; a unique constraint enforces no duplicates.
  - No data migration of existing rows — these tables start empty. Existing
    subscriptions continue to work unchanged.
*/

-- ============ pickups ============
CREATE TABLE IF NOT EXISTS smart_sort_pickups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL REFERENCES smart_sort_subscriptions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  scheduled_date date NOT NULL,
  time_slot text NOT NULL DEFAULT 'morning',
  driver_name text,
  route_order integer DEFAULT 0,
  status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','assigned','in_progress','completed','missed','cancelled')),
  completed_at timestamptz,
  notes text,
  photo_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE smart_sort_pickups ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_pickups_scheduled_date ON smart_sort_pickups(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_pickups_subscription_id ON smart_sort_pickups(subscription_id);

DROP POLICY IF EXISTS "select_own_pickups" ON smart_sort_pickups;
CREATE POLICY "select_own_pickups" ON smart_sort_pickups FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_select_all_pickups" ON smart_sort_pickups;
CREATE POLICY "admin_select_all_pickups" ON smart_sort_pickups FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

DROP POLICY IF EXISTS "insert_own_pickups" ON smart_sort_pickups;
CREATE POLICY "insert_own_pickups" ON smart_sort_pickups FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_pickups" ON smart_sort_pickups;
CREATE POLICY "update_own_pickups" ON smart_sort_pickups FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_update_all_pickups" ON smart_sort_pickups;
CREATE POLICY "admin_update_all_pickups" ON smart_sort_pickups FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

DROP POLICY IF EXISTS "delete_own_pickups" ON smart_sort_pickups;
CREATE POLICY "delete_own_pickups" ON smart_sort_pickups FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ invoices ============
CREATE TABLE IF NOT EXISTS smart_sort_invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL REFERENCES smart_sort_subscriptions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  invoice_number text UNIQUE NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  amount_sle integer NOT NULL,
  amount_paid_sle integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','partial','overdue','void')),
  due_date date NOT NULL,
  sent_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE smart_sort_invoices ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_invoices_status_due ON smart_sort_invoices(status, due_date);
CREATE INDEX IF NOT EXISTS idx_invoices_subscription_id ON smart_sort_invoices(subscription_id);

DROP POLICY IF EXISTS "select_own_invoices" ON smart_sort_invoices;
CREATE POLICY "select_own_invoices" ON smart_sort_invoices FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_select_all_invoices" ON smart_sort_invoices;
CREATE POLICY "admin_select_all_invoices" ON smart_sort_invoices FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_insert_invoices" ON smart_sort_invoices;
CREATE POLICY "admin_insert_invoices" ON smart_sort_invoices FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_invoices" ON smart_sort_invoices;
CREATE POLICY "admin_update_invoices" ON smart_sort_invoices FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

-- ============ payments ============
CREATE TABLE IF NOT EXISTS smart_sort_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL REFERENCES smart_sort_invoices(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  amount_sle integer NOT NULL,
  method text NOT NULL CHECK (method IN ('cash','bank_transfer','africell_money','orange_money','qmoney','other')),
  reference text,
  status text NOT NULL DEFAULT 'confirmed' CHECK (status IN ('pending','confirmed','failed')),
  recorded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE smart_sort_payments ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON smart_sort_payments(invoice_id);

DROP POLICY IF EXISTS "select_own_payments" ON smart_sort_payments;
CREATE POLICY "select_own_payments" ON smart_sort_payments FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_select_all_payments" ON smart_sort_payments;
CREATE POLICY "admin_select_all_payments" ON smart_sort_payments FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_insert_payments" ON smart_sort_payments;
CREATE POLICY "admin_insert_payments" ON smart_sort_payments FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_payments" ON smart_sort_payments;
CREATE POLICY "admin_update_payments" ON smart_sort_payments FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
  );
