/*
# Finance Pro: Invoices, FX Rates, Multi-Currency, Analytics

## Overview
Adds three new tables to support the Finance Module pro features:
1. Automated Invoicing & Statement Generation
2. Real-Time Revenue Analytics (via a database view)
3. Multi-Currency & FX Rate Management

## 1. New Tables

### `invoices`
Stores formal invoices generated by admins for clients.
- `id` (uuid PK)
- `user_id` (uuid, references auth.users) — the client being invoiced
- `invoice_number` (text, unique) — human-readable invoice number (e.g. INV-2026-0001)
- `status` (text) — draft | sent | paid | overdue | cancelled (default draft)
- `issue_date` (date) — date invoice was issued
- `due_date` (date) — payment deadline
- `currency` (text) — invoice currency code (default SLE)
- `subtotal` (numeric) — sum before tax
- `tax_rate` (numeric) — tax percentage (default 0)
- `tax_amount` (numeric) — computed tax
- `total` (numeric) — subtotal + tax_amount
- `amount_paid` (numeric) — amount already paid (default 0)
- `notes` (text) — optional notes
- `line_items` (jsonb) — array of {description, quantity, unit_price, total}
- `created_by` (text) — admin identifier
- `paid_at` (timestamptz) — when invoice was marked paid
- `created_at` / `updated_at` (timestamptz)

### `fx_rates`
Stores exchange rates between currencies and SLE (Sierra Leone Leone).
- `id` (uuid PK)
- `currency_code` (text, unique) — ISO 4217 code (USD, EUR, GBP, etc.)
- `currency_name` (text) — full name (e.g. US Dollar)
- `symbol` (text) — currency symbol ($, €, £)
- `rate_to_sle` (numeric) — 1 unit of this currency = X SLE
- `is_active` (boolean, default true)
- `updated_by` (text)
- `updated_at` (timestamptz)

### `revenue_daily` (view)
Aggregates daily revenue from wallet_transactions, monime_payments, and payment_receipts
for the analytics dashboard. Computed on the fly from source tables.

## 2. Security
- RLS enabled on `invoices` and `fx_rates`.
- `invoices`: admin full CRUD + client SELECT own invoices.
- `fx_rates`: admin full CRUD + client SELECT (rates are public to clients for display).
- The `revenue_daily` view is accessible to admins only (via is_admin()).

## 3. Important Notes
1. The `revenue_daily` view uses `is_admin()` in its WHERE clause so non-admins
   cannot read aggregate financial data through the view.
2. FX rates are stored as "1 foreign unit = X SLE" for easy conversion.
3. Invoice numbers auto-generate via a sequence-backed format.
4. All monetary columns use numeric(14,2) for precision.
*/

-- ── Sequence for invoice numbers ──
CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START 1;

-- ── invoices table ──
CREATE TABLE IF NOT EXISTS invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  invoice_number text UNIQUE NOT NULL DEFAULT ('INV-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('invoice_number_seq')::text, 4, '0')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','paid','overdue','cancelled')),
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NOT NULL DEFAULT (CURRENT_DATE + 14),
  currency text NOT NULL DEFAULT 'SLE',
  subtotal numeric(14,2) NOT NULL DEFAULT 0,
  tax_rate numeric(5,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  total numeric(14,2) NOT NULL DEFAULT 0,
  amount_paid numeric(14,2) NOT NULL DEFAULT 0,
  notes text,
  line_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_by text NOT NULL DEFAULT 'admin',
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_all_invoices" ON invoices;
CREATE POLICY "admin_select_all_invoices" ON invoices FOR SELECT
  TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

DROP POLICY IF EXISTS "select_own_invoices" ON invoices;
CREATE POLICY "select_own_invoices" ON invoices FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "admin_insert_invoices" ON invoices;
CREATE POLICY "admin_insert_invoices" ON invoices FOR INSERT
  TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

DROP POLICY IF EXISTS "admin_update_invoices" ON invoices;
CREATE POLICY "admin_update_invoices" ON invoices FOR UPDATE
  TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

DROP POLICY IF EXISTS "admin_delete_invoices" ON invoices;
CREATE POLICY "admin_delete_invoices" ON invoices FOR DELETE
  TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- ── fx_rates table ──
CREATE TABLE IF NOT EXISTS fx_rates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  currency_code text UNIQUE NOT NULL,
  currency_name text NOT NULL,
  symbol text NOT NULL DEFAULT '',
  rate_to_sle numeric(14,4) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  updated_by text NOT NULL DEFAULT 'admin',
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE fx_rates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_all_fx_rates" ON fx_rates;
CREATE POLICY "admin_select_all_fx_rates" ON fx_rates FOR SELECT
  TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

DROP POLICY IF EXISTS "client_select_active_fx_rates" ON fx_rates;
CREATE POLICY "client_select_active_fx_rates" ON fx_rates FOR SELECT
  TO authenticated USING (is_active = true);

DROP POLICY IF EXISTS "admin_insert_fx_rates" ON fx_rates;
CREATE POLICY "admin_insert_fx_rates" ON fx_rates FOR INSERT
  TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

DROP POLICY IF EXISTS "admin_update_fx_rates" ON fx_rates;
CREATE POLICY "admin_update_fx_rates" ON fx_rates FOR UPDATE
  TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

DROP POLICY IF EXISTS "admin_delete_fx_rates" ON fx_rates;
CREATE POLICY "admin_delete_fx_rates" ON fx_rates FOR DELETE
  TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

-- ── Seed default FX rates ──
INSERT INTO fx_rates (currency_code, currency_name, symbol, rate_to_sle) VALUES
  ('SLE', 'Sierra Leone Leone', 'SLE', 1.0000),
  ('USD', 'US Dollar', '$', 24.5000),
  ('EUR', 'Euro', '€', 26.3000),
  ('GBP', 'British Pound', '£', 30.1000)
ON CONFLICT (currency_code) DO NOTHING;

-- ── updated_at trigger for invoices ──
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS invoices_updated_at ON invoices;
CREATE TRIGGER invoices_updated_at BEFORE UPDATE ON invoices
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── revenue_daily view (admin-only aggregate) ──
DROP VIEW IF EXISTS revenue_daily;
CREATE VIEW revenue_daily AS
SELECT
  d::date AS date,
  COALESCE(w.topups, 0) AS wallet_topups,
  COALESCE(w.payments, 0) AS wallet_payments,
  COALESCE(m.monime_amount, 0) AS monime_amount,
  COALESCE(r.receipt_amount, 0) AS receipt_amount,
  (COALESCE(w.topups, 0) + COALESCE(m.monime_amount, 0) + COALESCE(r.receipt_amount, 0)) AS total_inflow,
  COALESCE(w.payments, 0) AS total_outflow
FROM generate_series(
  (date_trunc('day', now()) - interval '90 days')::date,
  date_trunc('day', now())::date,
  interval '1 day'
) AS d
LEFT JOIN (
  SELECT date_trunc('day', created_at)::date AS day,
    SUM(CASE WHEN type = 'topup' AND status = 'completed' THEN amount_sle ELSE 0 END) AS topups,
    SUM(CASE WHEN type = 'payment' AND status = 'completed' THEN ABS(amount_sle) ELSE 0 END) AS payments
  FROM wallet_transactions GROUP BY 1
) w ON w.day = d::date
LEFT JOIN (
  SELECT date_trunc('day', created_at)::date AS day,
    SUM(CASE WHEN status = 'completed' THEN amount_sle ELSE 0 END) AS monime_amount
  FROM monime_payments GROUP BY 1
) m ON m.day = d::date
LEFT JOIN (
  SELECT date_trunc('day', paid_at)::date AS day,
    SUM(amount_sle) AS receipt_amount
  FROM payment_receipts GROUP BY 1
) r ON r.day = d::date
WHERE is_admin();

GRANT SELECT ON revenue_daily TO authenticated;
